# ------------------------------------------------------------------------------
# ~/_config.yml
# Global Jekyll site configuration
#
# Product/Info:
# https://jekyll.one
#
# Copyright (C) 2016 Present, Themefisher
# Copyright (C) 2023 Juergen Adams
#
# Theme Parsa is licensed under the MIT License.
# See: https://github.com/themefisher/parsa-jekyll/blob/main/LICENSE
# Jekyll-Parsais licensed under the MIT License.
# See: https://github.com/jekyll-one-org/j1-template/blob/main/LICENSE.md
# ------------------------------------------------------------------------------

#-------------------------------------------------------------------------------
# General Site Settings

# The subpath of your site, e.g. /blog
#
baseurl:                                ''

# The base hostname & protocol for your site, e.g. http://example.com
#
url:                                    http://localhost:25000

title:                                  Parsa | Portfolio Jekyll Template
logo:                                   /assets/images/logo.png                 # You can add own logo
description:                                                                    # Add your awesome description
copyright:  >
                                        Copyright 2020 Designed by [Themefisher](https://themefisher.com) &
                                        Developed by [Gethugothemes](https://gethugothemes.com)

# Preloader
preloader:                              true # To disable preloader change value to false

menu:
  - name:                               Home
    url:                                /
  - name:                               All Posts
    url:                                /#all-posts
  - name:                               About
    url:                                /about/
  - name:                               Contact
    url:                                /contact/

# *** NOTE ***
# You can add submenus. For example:

#  menu:
#  - name: Home
#    url: /
#    submenu:
#     - name: Peru
#       url: /peru/
# ----------------------------------


#-------------------------------------------------------------------------------
# Layout Settings

# Homepage layout ( two layout is available, you can set the another layout by change the value of layout_home_page "true" to "false")
layout_home_page:                       true

# You can enable or disable the featured-post-slider using true or false values.
featured-post-slider:                   true

#-------------------------------------------------------------------------------
# Hero Section
hero:
  hero-subtitle: >
                                        I’m a Freelance Interactive Art Director based in France.
                                        Focusing across branding and identity, digital and print.
  # Add your banner image '/assets/images/'
  hero-banner:                          /assets/images/banner-img.png

#-------------------------------------------------------------------------------
# Author Settings
#
author:
  name:                                 Jhon Abraham

#-------------------------------------------------------------------------------
# Contact Info
#
contact:
  email:                                example@ymail.com
  phone:                                +90 000 333 22
  address:
    city:                               Sydney
    street:                             6 rip carl Avenue CA 90733

#-------------------------------------------------------------------------------
# Contact Form
#
contact-form:                           example@email.com

# Social links
social:
  - { icon: "ti-facebook", link: "#" }
  - { icon: "ti-twitter-alt", link: "#" }
  - { icon: "ti-linkedin", link: "#" }
  - { icon: "ti-github", link: "#" }

#-------------------------------------------------------------------------------
# Comment Section (Disqus)
disqus-identifier:                                                              # Add your shortname for Disqus Comment. For example mr-brown

#-------------------------------------------------------------------------------
# Instagram Feed
#
# To enable the instafeed, use the value true. To turn off use the value false.
instafeed:                              false
userID:                                 4044026246
accessToken:                            4044026246.1677ed0.8896752506ed4402a0519d23b8f50a17

#-------------------------------------------------------------------------------
# Google Analytics
#
google-analytics:                                                               # Add your identifier. For example UA-99631805-1.

#-------------------------------------------------------------------------------
# Build settings
permalink:                              pretty

# ------------------------------------------------------------------------------
# WEBRICK Customizations
# You can provide custom headers for your site
# See: https://jekyllrb.com/docs/configuration/webrick/
#      https://developer.mozilla.org/en-US/docs/Web/HTTP/CSP
#
# NOTE:
# Jekyll provides by default Content-Type and Cache-Control
# response headers: one dynamic in order to specify the nature of
# the data being served, the other static in order to disable
# caching so that you don’t have to fight with Chrome’s aggressive
# caching when you are in development mode.
#
# webrick:
#   headers:
#     My-Header: My-Value
#     My-Other-Header: My-Other-Value
#
# ------------------------------------------------------------------------------
#
webrick:
  headers:
    X-Builder-Template:                 J1 Theme
    X-Builder-Engine:                   Jekyll

# ------------------------------------------------------------------------------
# POSTS Management
# Control how post articles are generated
#
future:                                 true                                    # workaround (non US) TZ issues (of April 2021)
show_drafts:                            false
unpublished:                            false
limit_posts:                            1000000                                 # set to UNLIMITED

# ------------------------------------------------------------------------------
# LIQUID template engine
#
liquid:
  error_mode:                           warn

# ------------------------------------------------------------------------------
# MARKDOWN
#
# NOTE:
#   Option input/GFM turns on the recognition of Github Flavoured
#   Markdown (GFM)
#
markdown:                               kramdown
markdown_ext:                           markdown,md

kramdown:
  input:                                GFM
  auto_ids:                             true
  footnote_nr:                          1
  entity_output:                        as_char
  toc_levels:                           1..3
  smart_quotes:                         lsquo,rsquo,ldquo,rdquo
  syntax_highlighter:                   rouge

# ------------------------------------------------------------------------------
# PLUGIN configuration
#
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-archives

# ------------------------------------------------------------------------------
# Paginator V1 configuration
#
paginate:                               10
paginate_path:                          "/page/:num"

# Pages Path
defaults:
  - scope:
      path:                             "_pages"
    values:
      permalink:                        /:basename:output_ext

include:
  - _pages

# Tags
tag_page_dir:                           tag
tag_page_layout:                        tag_page
tag_permalink_style:                    pretty

# Categories
jekyll-archives:
  enabled:                              all
  layout:                               category
  permalinks:
    category:                           "/category/:name/"

# ------------------------------------------------------------------------------
# FILES configuration
# Set the files to include, exclude and ignore (keep_files on _site)
#
include:                                [ .htaccess ]
exclude:                                [
                                          log, Gemfile, Gemfile.lock, yarn.lock,
                                          node_modules,
                                          vendor, '.sass-cache', '.vscode', '.idea',
                                          package-lock.json, package.json,
                                          '*.ignore',
                                          '*.bat', '*.sh', '*.tmp', 'dot.*',
                                          '*.txt', '*.log', '*.ppt*', '*.pdf',
                                          '*.zip', '*.7z', '*.tgz', '*.tar'
                                        ]

# ------------------------------------------------------------------------------
# SASS conversion options
#
# Sets the style of the generate CSS file.
# Possible values: compact|compressed|expanded|nested
#
sass:
  sass_dir:                             _sass
  style:                                expanded                                # nested | expanded | compact | compressed
# verbose:                              true
