# ------------------------------------------------------------------------------
# ~/_config.yml
# Global Jekyll site configuration
#
# Product/Info:
# https://jekyll.one
#
# Copyright (C) 2016 Present, Themefisher
# Copyright (C) 2023 Juergen Adams
#
# Theme Parsa is licensed under the MIT License.
# See: https://github.com/themefisher/parsa-jekyll/blob/main/LICENSE
# Jekyll-Parsais licensed under the MIT License.
# See: https://github.com/jekyll-one-org/j1-template/blob/main/LICENSE.md
# ------------------------------------------------------------------------------

# ==============================================================================
# 4. JEKYLL specific site configuration
#
# ------------------------------------------------------------------------------
#
permalink:                              pretty

# The base hostname & protocol for your site, e.g. http://example.com
#
# url:                                  http://localhost:25000
url:                                    https://jekyll-parsa.netlify.app/


# The subpath of your site, e.g. /blog
#
baseurl:                                ''

# The production_url is only used when full-domain names are needed
# such as sitemap.txt. For most places will/should use base_path to
# make the URLs.
#
base_path:                              ''

# ------------------------------------------------------------------------------
# Base hostname and protocol for the site
#
#  Defaults:
#   protocol:                           http
#   host:                               localhost
#   port:                               4000
#   timezone:                           Europe/Berlin
#   encoding:                           UTF-8
#
protocol:                               http
host:                                   localhost
port:                                   25000
timezone:                               Europe/Berlin
encoding:                               UTF-8

# detach:                               false
# show_dir_listing:                     true


# ------------------------------------------------------------------------------
# PATH configuration
# Global folder configuration where Jekyll will read files from
#
#  Defaults:
#   source:                             .
#   destination:                        _site
#
source:                                 .
destination:                            _site
plugins_dir:                            _plugins
layouts_dir:                            _layouts
data_dir:                               _data
includes_dir:                           _includes
collections_dir:                        collections


# ==============================================================================
# 3. SITE configuration
#
# ------------------------------------------------------------------------------
#
title:                                  Parsa | Jekyll Portfolio Template
logo:                                   /assets/images/parsa/icons/logo.svg            # You can add own logo
description:                                                                    # Add your awesome description
copyright:  >
                                        Copyright 2023, All right reserved &nbsp;&nbsp;&middot;&nbsp; Designed by [Themefisher](https://themefisher.com)
                                        &nbsp;&nbsp;&middot;&nbsp;Developed by [JekyllOne](https://jekyll.one)

# Preloader
# To disable preloader change value to false
# ------------------------------------------------------------------------------
#
preloader:                              true

# Navigation
# Nav menu entries
# ------------------------------------------------------------------------------
#
menu:
  - name:                               Portfolio
    url:                                /#portfolio
  - name:                               Featured
    url:                                /#featured-posts
  - name:                               All Posts
    url:                                /#all-posts
  - name:                               Contact
    url:                                /contact/
  - name:                               About
    url:                                /about/

# *** NOTE ***
# You can add submenus. For example:
# ------------------------------------------------------------------------------
#  menu:
#  - name: Home
#    url: /
#    submenu:
#     - name: Peru
#       url: /peru/
# ------------------------------------------------------------------------------


#-------------------------------------------------------------------------------
# Layout Settings

# Homepage layout ( two layout is available, you can set the another
# layout by change the value of layout_home_page "true" to "false")
layout_home_page:                       true

# You can enable or disable the featured-post-slider using true or
# false values.
featured-post-slider:                   true

#-------------------------------------------------------------------------------
# Hero Section
hero:
  hero-subtitle: >
                                        I’m a Freelance Art Director based in France.
                                        Focusing across branding and identity, digital
                                        and print.
  # Add your banner image
  hero-banner:                          /assets/images/parsa/masthead/banner-img.png

#-------------------------------------------------------------------------------
# Author Settings
#
author:
  name:                                 Jhon Abraham

#-------------------------------------------------------------------------------
# Contact Info
#
contact:
  email:                                example@ymail.com
  phone:                                +90 000 333 22
  address:
    city:                               Sydney
    street:                             6 rip carl Avenue CA 90733

#-------------------------------------------------------------------------------
# Contact Form
#
contact-form:                           example@email.com

# Social links
#
social:
  - { icon: "ti-github", link: "https://github.com/jekyll-one/jekyll-parsa" }
  - { icon: "ti-facebook", link: "https://www.facebook.com/" }
  - { icon: "ti-twitter-alt", link: "https://twitter.com/home" }
  - { icon: "ti-linkedin", link: "https://www.linkedin.com/" }


#-------------------------------------------------------------------------------
# Comment Section (Disqus)
# Add your shortname for Disqus Comment. For example mr-brown
#
disqus-identifier:

#-------------------------------------------------------------------------------
# Instagram Feed
# To enable the instafeed, use the value true. To turn off use the value false.
#
instafeed:                              false
userID:                                 4044026246
accessToken:                            4044026246.1677ed0.8896752506ed4402a0519d23b8f50a17

#-------------------------------------------------------------------------------
# Google Analytics
# Add your identifier. For example UA-99631805-1.
#
google-analytics:

#-------------------------------------------------------------------------------
# Build settings
markdown:                               kramdown

# ------------------------------------------------------------------------------
# PLUGIN configuration
#
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-archives

# ------------------------------------------------------------------------------
# Paginator V1 configuration
#
paginate:                               6
paginate_path:                          /page/:num

# Pages Path
#
defaults:
  - scope:
      path:                             pages
    values:
      permalink:                        /:basename:output_ext

# Categories
#
jekyll-archives:
  enabled:                              all
  layout:                               category
  permalinks:
    category:                           /category/:name/

# Tags
#
# tag_page_dir:                           tag
# tag_page_layout:                        tag_page
# tag_permalink_style:                    pretty

# ------------------------------------------------------------------------------
# FILES configuration
# Set the files to include, exclude and ignore (keep_files on _site)
#
include:                                [ .htaccess ]
exclude:                                [
                                          log, Gemfile, Gemfile.lock, yarn.lock,
                                          node_modules,
                                          vendor, '.sass-cache', '.vscode', '.idea',
                                          package-lock.json, package.json,
                                          '*.ignore',
                                          '*.bat', '*.sh', '*.tmp', 'dot.*',
                                          '*.txt', '*.log', '*.ppt*', '*.pdf',
                                          '*.zip', '*.7z', '*.tgz', '*.tar'
                                        ]

# ------------------------------------------------------------------------------
# SASS conversion options
#
# Sets the style of the generate CSS file.
# Possible values: compact|compressed|expanded|nested
#
sass:
  sass_dir:                             _sass
  style:                                expanded                                # nested | expanded | compact | compressed
# verbose:                              true


# ==============================================================================
# 6. PAGE configuration
#
# ------------------------------------------------------------------------------
#
# ------------------------------------------------------------------------------
# EXCERPT settings
#
excerpt_separator:                      excerpt__end
excerpt_truncate_words:                 100

# ------------------------------------------------------------------------------
# COLLECTION settings
# See: https://jekyllrb.com/docs/collections/#collections
#
collections:

  # ----------------------------------------------------------------------------
  # Agency
  #
  portfolio:
    output: true

# ------------------------------------------------------------------------------
# FRONTMATTER defaults
#
# Using the YAML Front Matter is a way the (individual) configuration
# for post and pages can be specified. Very often, a lot of config
# options are repeated on each and every post or page. Setting the
# layout for each file, adding categories to a post, etc. might be
# the same for the majority of your content.
#
# Instead of repeating this configuration each time a page is being
# created, Jekyll provides a way to set these configuration items
# as defaults in this site configuration (_config.yml).
#
defaults:

  # ----------------------------------------------------------------------------
  # HTML partials (loaded via XHR) excluded from sitemap
  #
  - scope:
      path:                             assets/data

    values:
      sitemap:                          false

  # ----------------------------------------------------------------------------
  # Module HTML docs and examples excluded from sitemap
  #
  - scope:
      path:                             assets/themes/j1

    values:
      sitemap:                          false

  # ----------------------------------------------------------------------------
  # PAGES
  #
  - scope:
      path:                             pages
      type:                             pages

    values:
      layout:                           page
      compress:                         true

      author:
        name:                           Juergen Adams
        url:                            https://jekyll.one/

      icons:
        family:                         MDI
        color:                          md-blue
        size:                           5x

      images:
        dir:                            /assets/images/parsa/pages

      robots:
        index:                          true
        follow:                         true

      toc:                              true
      fab_menu_id:                      page_ctrl
      scrollbar:                        false
      personalization:                  false
      exclude_from_search:              false

      youtube:                          true
      vimeo:                            true

      resource_options:
        - toccer:
            collapseDepth:              3

  # ----------------------------------------------------------------------------
  # POSTS
  #

  # ----------------------------------------------------------------------------
  # PUBLIC - FEATURED
  #
  - scope:
      path:                             posts
      type:                             posts

    values:
      layout:                           post
      compress:                         true

      author:
        name:                           Juergen Adams
        url:                            https://jekyll.one/

      robots:
        index:                          true
        follow:                         true

      toc:                              true
      fab_menu_id:                      open_toc_reload
      scrollbar:                        false
      page_navigation:                  true
      personalization:                  false
      exclude_from_search:              false
      series:                           false

      resource_options:
        - toccer:
            collapseDepth:              3

# ------------------------------------------------------------------------------
# END config
